const Routes = {
  baseUrl: "https://portalfare-server.herokuapp.com/api/v1",
  imageUrl: "https://portalfare-server.herokuapp.com/",
  // imageUrl: "http://localhost:5000/",
  // baseUrl: "http://localhost:5000/api/v1",
  login: "/auth/login",
  authUser: "/auth/auth-user",
  passReset: "/auth/reset",
  Notifications: "/admin/notifications",
  activateUser: "/admin/activateUser/",
  deActivateUser: "/admin/deactivateUser/",
  activateAgent: "/admin/activateAgent/",
  deActivateAgent: "/admin/deactivateAgent/",
  adminPassChange: "/admin/change",
  deleteUser: "/admin/delete-user/",
  deleteAgent: "/admin/delete-agent/",
  getUser: "/admin/get-user/",
  updateUser: "/admin/update-user/",
  allUsers: "/admin/all-user",
  allAgents: "/admin/all-agent",
  blockUser: "/admin/block/:userId",
  unBlockUser: "/admin/unblock/:userId",
  addAgent: "/agent",
  user: "/user",
  ticket: "/ticket",
  createTicket: "/create",
  updateTicket: "/update/",
  allTicket: "/alltickets",
  myTickets: "/mytickets",
  deltedTicket: "/delete/",
  TicketByID: "/ticket/",
  approveTicket: "/approve/",
  rejectTicket: "/reject/",
  totalTicket: "/totalticket",
  uploadRequiredNames: "/requiredNames/upload",
  AllRequiredNames: "/requiredNames/allNames",
  AllMyRequiredNames: "/requiredNames/allMyNames",
  DeleteName: "/requiredNames/delete/",
  GetOneName: "/requiredNames/getOne/",
  createGroup: "/group/create",
  updateGroup: "/group/update/",
  allGroups: "/group/allgroups",
  myGroups: "/group/mygroups",
  deltedGroup: "/group/delete/",
  adminDeltedGroup: "/group/admin/delete/",
  GroupByID: "/group/group/",
  approveGroup: "/group/approve/",
  rejectGroup: "/group/reject/",
  totalGroups: "/group/totalgroups",
  logout: "/auth/logout/",
  statistics: "/admin/statistics",
  updatePNR: "/user/updatepnr",
  // baseUrl:"https://portalfare-server.herokuapp.com/api/v1",
  // baseUrl:"https://portalfare-server.herokuapp.com/api/v1",
  // baseUrl:"https://portalfare-server.herokuapp.com/api/v1",
  // baseUrl:"https://portalfare-server.herokuapp.com/api/v1",
};
export default Routes;
